version: '3.8'

services:

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.multistage
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
