# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:1.21 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/*.go ./

RUN GOARCH=arm64 CGO_ENABLED=0 GOOS=linux go build -o /server

# Deploy the application binary into a lean image
FROM debian AS build-release-stage

WORKDIR /

COPY --from=build-stage /server /server

EXPOSE 8080

ENTRYPOINT ["/server"]