version: '3.8'

services:

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      AZURE_COSMOS_ENDPOINT: "x"
      AZURE_COSMOS_KEY: "x"
      AZURE_COSMOS_DB: "x"
      AZURE_COSMOS_CONTAINER: "x"